/**
 * Series generation, and the statement of method C4-IV-06 requires.
 *
 * THE METHOD, stated here, in the method panel on the page, and in the
 * structured object: each point is computed from the TOP POINT and its INTEGER
 * INDEX, by exponentiation by squaring on the index, followed by one division.
 * Point i is `top / f^(i-1)`, and `f^(i-1)` is built by repeated squaring of f.
 *
 * WHY NOT `Math.pow`. ECMAScript does not require `Math.pow` to be correctly
 * rounded and it is engine-dependent. Measured pow-generated and
 * multiply-generated 12-point series at a factor of 3 differ by about 1 ULP,
 * and the pow series shows consecutive-ratio error of plus or minus 0.67 ULP at
 * several points. C4-ST-05 claims determinism within one engine and claims
 * cross-engine agreement only within the derived tolerance UNLESS the method is
 * shown to be engine-independent. Exponentiation by squaring is a fixed
 * sequence of IEEE 754 multiplications, each of which every conforming engine
 * must round correctly, so the sequence is identical everywhere and the
 * stronger claim is available.
 *
 * WHY NOT REPEATED MULTIPLICATION from the previous point. It accumulates: each
 * step inherits the rounding of every step before it, and by point 12 the
 * consecutive ratio has drifted. C4-IV-05 confirms the ratio test can detect
 * exactly that, by generating a series that way on purpose.
 *
 * The C4-IV-03 tolerance is derived over THIS method and no other. A change
 * here invalidates the derivation, not merely the numbers.
 */

/**
 * `base` raised to a non-negative integer power, by exponentiation by squaring.
 *
 * A fixed sequence of correctly rounded multiplies, and therefore identical
 * across conforming engines. The number of multiplications depends only on the
 * bit pattern of the exponent, so it is the same sequence for every caller at a
 * given index.
 */
export function integerPower(base: number, exponent: number): number {
  if (!Number.isInteger(exponent) || exponent < 0) {
    throw new Error(`integerPower expects a non-negative integer exponent, received ${exponent}`)
  }
  let result = 1
  let square = base
  let remaining = exponent
  while (remaining > 0) {
    if (remaining % 2 === 1) result *= square
    remaining = Math.floor(remaining / 2)
    if (remaining > 0) square *= square
  }
  return result
}

/**
 * The value at a one-based point index of a descending series.
 *
 * One division by the exact integer power, rather than a running product, so
 * that no point inherits another point's rounding. Point 1 divides by 1 and is
 * therefore the top point unchanged, bit for bit, which is what lets C4-SR-03's
 * index-1 guarantee be an identity rather than an approximation.
 */
export function seriesValue(top: number, factor: number, index: number): number {
  if (!Number.isInteger(index) || index < 1) {
    throw new Error(`seriesValue expects a one-based integer index, received ${index}`)
  }
  return top / integerPower(factor, index - 1)
}

/** The whole series, in descending concentration order, index 1 first. */
export function series(top: number, factor: number, points: number): number[] {
  return Array.from({ length: points }, (_, i) => seriesValue(top, factor, i + 1))
}

/**
 * The method statement, displayed with the result per C4-IV-06 and carried in
 * the structured object so a consumer knows which derivation the tolerance
 * belongs to.
 */
export const GENERATION_METHOD =
  'Each point is computed from the top point and its integer index as top / f^(i-1), ' +
  'with f^(i-1) formed by exponentiation by squaring and applied as a single division. ' +
  'Math.pow is not used: it is not required to be correctly rounded and is engine-dependent. ' +
  'Points are not generated by repeated multiplication from the preceding point, which would ' +
  'accumulate rounding along the series.'
